<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="title" type="xs:string" />
  <xs:element name="description" type="xs:string">
    <xs:annotation>
      <xs:documentation xml:lang="en">Description of an exam object or a question object.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:simpleType name="QuestionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="single-choice" />
      <xs:enumeration value="multiple-choice" />
      <xs:enumeration value="drag-and-drop" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="option">
    <xs:annotation>
      <xs:documentation xml:lang="en">Representing an option in a single-choice or multiple-choice question. The &#x60;id&#x60; attribute have to be unique within the question scope.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="id" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="options">
    <xs:annotation>
      <xs:documentation xml:lang="en">A options enclosure is simply a container of options</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="option" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="combination">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="option" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="connect">
    <xs:annotation>
      <xs:documentation xml:lang="en">Represent a connection line in Cisco-flavor drag-and-drop exam question.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="dst" type="xs:string" use="required" />
      <xs:attribute name="src" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="connections">
    <xs:annotation>
      <xs:documentation xml:lang="en">A connections object is simply a container of a list of connects that occurs in a submitting answer.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connect" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="connectsource">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="connectdestination">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="connectcombination">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connectsource" minOccurs="1" maxOccurs="unbounded" />
        <xs:element ref="connectdestination" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="connectionsolution">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connect" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="connectcombination" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="requiredUniqueConnections" type="xs:integer" use="required">
        <xs:annotation>
          <xs:documentation>Dictating the fixed number of unique connections to make the answer to be valid</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="connectionsolutions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connectionsolution" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="correctanswer">
    <xs:annotation>
      <xs:documentation xml:lang="en">A correctanswer object must contain enough information to enable it to test the correctness of submitting answer.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="options" minOccurs="0" maxOccurs="1" />
        <xs:element ref="combination" minOccurs="0" maxOccurs="1" />
        <xs:element ref="connectionsolutions" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:attribute name="src" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="exhibit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="image" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="exhibits">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exhibit" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="candidate">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="id" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="candidates">
    <xs:annotation>
      <xs:documentation xml:lang="en">Represent a drag-and-drop source area</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="candidate" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="drop">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="id" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="drops">
    <xs:annotation>
      <xs:documentation xml:lang="en">Represent a drag-and-drop drop area</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="drop" minOccurs="1" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="droparealabel">
    <xs:annotation>
      <xs:documentation>Represent a label in a drop area</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="droparea">
    <xs:annotation>
      <xs:documentation xml:lang="en">Represent a drop section in a multi-subsection drops</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="droparealabel" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="drop" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="multiareadrop">
    <xs:annotation>
      <xs:documentation xml:lang="en">Represent a drag-and-drop drop area that was divided into multiple sub-sections</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="droparea" minOccurs="1" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="question">
    <xs:annotation>
      <xs:documentation xml:lang="en">A question enclosure models a Cisco-flavor exam question: like a single-choice, a multiple-choice or a drag-and-drop question. The &#x60;id&#x60; attribute of the question has to be unique within the surrounding question collection scope.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" />
        <xs:element ref="exhibits" minOccurs="0" maxOccurs="1" />
        <xs:element ref="options" minOccurs="0" maxOccurs="1" />
        <xs:element ref="candidates" minOccurs="0" maxOccurs="1" />
        <xs:element ref="multiareadrop" minOccurs="0" maxOccurs="1" />
        <xs:element ref="drops" minOccurs="0" maxOccurs="1" />
        <xs:element ref="correctanswer" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="type" type="QuestionType" />
      <xs:attribute name="score" type="xs:float" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="questioncollection">
    <xs:annotation>
      <xs:documentation xml:lang="en">A question collection is just a ordered list of questions</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="question" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="questionset">
    <xs:annotation>
      <xs:documentation xml:lang="en">A question set can have one or more question collections, to allow picking up a random question collection when starting a new exam.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="questioncollection" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="exam">
    <xs:annotation>
      <xs:documentation xml:lang="en">An exam is a container that contains a set of question collections that focus on a specific topic.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" />
        <xs:element ref="description" />
        <xs:element name="passingscore" minOccurs="0" maxOccurs="1" type="xs:float" />
        <xs:element ref="questionset" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="shortname" type="xs:string" />
      <xs:attribute name="code" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="answer">
    <xs:annotation>
      <xs:documentation xml:lang="en">Answer targeting a single question</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="options" minOccurs="0" maxOccurs="1" />
        <xs:element ref="connections" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="questionId" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">The &#x60;questionId&#x60; attribute targeting a specific question within a question collection which is specified by the parent examanswer object.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="questionType" type="QuestionType" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">Specify the question type in the attribute of an answer object to facilitate the validation of the schema of a submitting answer.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="examanswer">
    <xs:annotation>
      <xs:documentation xml:lang="en">An examanswer enclosure represents a submitting answer targeting the whole exam paper of the selected question collection index, the exam server use the correctanswer as defined in the question object to validate the correctness of the submitting answer.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="answer" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="OverallResultType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="pass" />
      <xs:enumeration value="immediate" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="overallresult" type="OverallResultType" />
  <xs:element name="scoreresult">
    <xs:complexType>
      <xs:attribute name="earnedScore" type="xs:float" use="required" />
      <xs:attribute name="totalScore" type="xs:float" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="questionscore">
    <xs:complexType>
      <xs:attribute name="questionId" type="xs:string" />
      <xs:attribute name="scoreEarned" type="xs:float" />
    </xs:complexType>
  </xs:element>
  <xs:element name="assessment">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="overallresult" minOccurs="0" maxOccurs="1" />
        <xs:element ref="scoreresult" minOccurs="0" maxOccurs="1" />
        <xs:element ref="questionscore" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exam" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="examanswer" minOccurs="0" maxOccurs="1" />
        <xs:element ref="assessment" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>